// Original file name: CardBeam.h
// Generated by piBuilder @ 08/09/2004 14:49:13

#define CardBeam 1
#define AppVersion 1000
#define ListView 3
#define BeamButton 4
#define CardTable 5
#define UpButton 6
#define DownButton 7
#define ListViewMenu 8
#define AboutDialog 9
#define AboutOkButton 10
#define AboutLabel 11
#define CardBeamHelpString 12
#define ListViewOptionsAboutMenu 13
#define BeamAllDialog 1001
#define BeamAllButton 1002
#define PushButtonTXT 1003
#define PushButtonVCS 1004
#define PushButtonVCF 1005
#define PushButtonPRC 1006
#define PushButtonOther 1007
#define BeamAllOkButton 1008
#define BeamAllExtField 1009
#define BeamAllCancelButton 1011
#define CardSelectTrigger 1012
#define CardSelectList 1013
