// Original file name: CardBeam.h
// Generated by piBuilder @ 16/01/2004 11:47:46

#define CardBeam 1
#define AppVersion 1000
#define ListView 3
#define BeamButton 4
#define CardTable 5
#define UpButton 6
#define DownButton 7
#define ListViewMenu 8
#define AboutDialog 9
#define AboutOkButton 10
#define AboutLabel 11
#define CardBeamHelpString 12
#define ListViewOptionsAboutMenu 13
